name: itvlist

on:
  schedule:
    - cron: '0 4,10,22 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
      #  run: pip install selenium requests futures eventlet
        run: pip3 install beautifulsoup4-4.12.3-py3-none-any.whl
             pip3 install requests

      - name: Run a
        run: python ${{ github.workspace }}/so.py
     
       
      - name: 提交更改
        run: |
          git config --local user.email "yongshou96@gmail.com"
          git config --local user.name "yong739"
          git add .
          git commit *.txt -m "Add generated file"
          git commit *.m3u -m "Add generated file"
          #git pull --rebase
          git push -f
